<?php 

/**
 * Implements hook_menu()
 */
function nodemanager_menu() {
	
	$items['admin/content/nodemanager'] = array(
    'title' => t('Node manager'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('nodemanager_form'),
    'access callback' => TRUE,
    'access arguments' => array('observe nodes'),
    'file' => 'includes/nodemanager.tool.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  
  return $items;
}

/**
 * Implementation of hook_permission().
 */
function nodemanager_permission() {
  return array(
    'manage nodes' => array(
      'title' => t('Right to administer nodes'),
    ),
		'observe nodes' => array(
				'title' => t('Right to access node manager'),
			),
  );
}

/**
 * Implementation of hook_mail().
 */
function nodemanager_mail($key, &$message, $params) {
  
  switch($key) {
		case 'nodemanager_mail':
			$message['subject'] = $params['subject'];
			$message['body'] = $params['body'];
			$message['headers'] = array_replace($message['headers'], $params['headers']);
			break;
	}
}